import styled from "styled-components";
export const ProductsContainer = styled.div``;
export const ProductsHeading = styled.h1``;
export const ProductsWrapper = styled.div``;
export const ProductCard = styled.div``;
export const ProductInfo = styled.div``;
export const ProductTitle = styled.h2``;
export const ProductDesc = styled.p``;
export const ProductPrice = styled.p``;
export const ProductImg = styled.img``;
export const ProductButton = styled.button``;
